branches:
    only:
        - master
        - dev
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -r requirements-dev.txt
    - pip install --editable .
    - pip install tox-travis
    - pip install coveralls
script:
    - flake8
    - pylint curver.kernel
    - tox -- --hypothesis-profile=ci
after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then coveralls; fi
deploy:
    provider: pypi
    user: mark_bell
    password:
        secure: "QMqoEhZEDQXIQcfcn+PSIjoKDjfiEN28H6vts/G57hSHhNd2gDorxQCb3y0KXSGe4mfWFAqxZXqgiQcHxKHSAlAKfOszCPXwSnONlxcnDzUYjgIfAlw0JBCfC9JYm+8+aaIV3Y/f4iZAUo38OG44mayhocNEgbKuU4xxljMVkZD2kMgHtTKzJg0rzjSdgscoFUjUhW8qcFET6aiZ1rwFORzGm7x9zNDEHRP1LUErLsa6gV6faDGVGYJAZyuXX9iZoP+MsMdgs3djG1Aa0UjdjeHmBro9SS+GCER989xOBiU6a/7Z8Q6ZnZ8m8NVlilvRGmYzaknBn9tJzly3p1LCuSonNrW3ZttxqA/ptNjk006wltcMRl5sPnXs+MmLQUTRBndXmSH0ixuGVGEJZiNTFvie6Qj0uwF4U672n7eNbdyvT2eyqPFQHJPK/tbCyVTdx8m4lRC0KgTtEg/3OlVPDRgC20ajFeWF6necYXylhjXcs+GvKoMAEd/3XhNz0azZoqX4aeLleiMlzh+ZjIr6N+TIkAOfyN0vy0qG3B9WcAdYtpWerIbAy4NMgFcUs3vG6/J8AePAWcBa7J6QPKeoQzmNdbJsiYo3kFrUV0y6TA/zZ4gBAQE+IIJQDNFJwRNW82oc6QWqXkWEDlViKeWmDjhhBZRdWwyOIcFixAg44rM="
    on:
        tag: true
        branch: master
        condition: $TRAVIS_PYTHON_VERSION == 2.7
