
language: python
python:
    - 2.7
    - 3.6
install:
    - pip install -r requirements-dev.txt
    - pip install --editable .
script:
    - py.test --cov=curver/kernel
after_success:
    - coveralls

