
language: python
python:
    - 2.7
    - 3.6
install:
    - pip install pytest pytest-cov
    - pip install hypothesis
    - pip install coveralls
    - pip install --editable .
script:
    - py.test --cov=curver/kernel
after_success:
    - coveralls

