
build: false

branches:
  only:
  - master
  - dev

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python34"
      TOX_ENV: "py34"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

init:
  - ECHO %PYTHON%
  - %PYTHON%/python.exe -c "import sys; print(sys.version)"

install:
  - %PYTHON%/Scripts/pip.exe install -r requirements-dev.txt
  - %PYTHON%/Scripts/pip.exe install --editable .

test_script:
  - %PYTHON%/Scripts/flake8.exe
  - %PYTHON%/Scripts/pylint.exe curver.kernel
  - %PYTHON%/Scripts/tox.exe -e %TOX_ENV% -- --hypothesis-profile=ci

