
build: false

environment:
  matrix:
    - PYTHON: "C:\\Python37"
      TOX_ENV: "docs"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "lint"

    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python35"
      TOX_ENV: "py35"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

    - PYTHON: "C:\\Python37"
      TOX_ENV: "py37"

init:
  - set "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - echo "%PYTHON%"
  - python -c "import sys; print(sys.version)"
  - pip --version

install:
  - pip install pip --upgrade --user
  - pip install setuptools virtualenv --upgrade
  - pip install tox

test_script:
  - tox -e %TOX_ENV% -- --hypothesis-profile=ci --durations=20

